# Generated by Django 6.1 on 2026-08-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
