# Generated by Django 6.1 on 2026-08-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='descriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='descriptions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='video_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movievideo',
            name='video_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
